```{r basics}
# [demo ELC] basics
basic <- list(
  title='Demo of Equal Loudness Curve',
  author='Andy',
  date='Dec 2024',
  ref=c('https://cdn.standards.iteh.ai/samples/83117/6afa5bd94e0e4f32812c28c3b0a7b8ac/ISO-226-2023.pdf')
)
```

```{r read}
# [demo ELC] load parameter table
raw_param_table <- '
freq,alpha_f,L_U,T_f
20,0.635,-31.5,78.1
25,0.602,-27.2,68.7
31.5,0.569,-23.1,59.5
40,0.537,-19.3,51.1
50,0.509,-16.1,44.0
63,0.482,-13.1,37.5
80,0.456,-10.4,31.5
100,0.433,-8.2,26.5
125,0.412,-6.3,22.1
160,0.391,-4.6,17.9
200,0.373,-3.2,14.4
250,0.357,-2.1,11.4
315,0.343,-1.2,8.6
400,0.330,-0.5,6.2
500,0.320,0.0,4.4
630,0.311,0.4,3.0
800,0.303,0.5,2.2
1000,0.300,0.0,2.4
1250,0.295,-2.7,3.5
1600,0.292,-4.2,1.7
2000,0.290,-1.2,-1.3
2500,0.290,1.4,-4.2
3150,0.289,2.3,-6.0
4000,0.289,1.0,-5.4
5000,0.289,-2.3,-1.5
6300,0.293,-7.2,6.0
8000,0.303,-11.2,12.6
10000,0.323,-10.9,13.9
12500,0.354,-3.5,12.3
'
dat <- read_csv(raw_param_table, col_types='dddd')
dat <- lapply(dat, function(col) col)
```

```{r out}
index_by_numeric_key <- function(S, k) { return(S[[as.character(k)]]) }
freq <- dat[['freq']]
alpha_f_ <- setNames(dat[['alpha_f']], freq)
alpha_f <- function(freq) { return(index_by_numeric_key(alpha_f_, freq)) }
L_U_ <- setNames(dat[['L_U']], freq)
L_U <- function(freq) { return(index_by_numeric_key(L_U_, freq)) }
T_f_ <- setNames(dat[['T_f']], freq)
T_f <- function(freq) { return(index_by_numeric_key(T_f_, freq)) }
```

```{r plot}
# [demo ELC] plot equal loudness curve
library(ggplot2)
library(tidyr)

L_f <- function(L_N, alpha_f, L_U, T_f) {
  return(10 / alpha_f * log10(4e-10 ^ (0.3 - alpha_f) * (10 ^ (0.03 * L_N) - 10 ^ 0.072) + 10 ^ (alpha_f * (T_f + L_U) / 10)) - L_U)
}
L_N <- function(L_f, alpha_f, L_U, T_f) {
  return(100 / 3 * log10((10 ^ (alpha_f * (L_f + L_U) / 10) - 10 ^ (alpha_f * (T_f + L_U) / 10)) / (4e-10 ^ (0.3 - alpha_f)) + 10 ^ 0.072))
}

Phon <- seq(from=0, to=100, by=10)

D <- list('freq'=freq)
for (p in Phon) {
  p_ <- as.character(p)
  tmp <- list()
  for (f in freq) {
    tmp[[length(tmp) + 1]] <- L_f(p, alpha_f(f), L_U(f), T_f(f))
  }
  D[[p_]] <- unlist(tmp)
}

print(D[['freq']])
print(D[['0']])

chart <- ggplot() +
  geom_line(aes(x=D[['freq']], y=D[['0']]))
print(chart)
```
