```{r basics}
# [7420 pw] input basics
basic <- list(
  "this" = list(
    "title" = "Exynos 7420 Power Curves",
    "author" = "Andy",
    "date" = "2024-12"
  ),
  "src" = list(
    "page_title" = "CPU Power Consumption",
    "title" = "The Samsung Exynos 7420 Deep Dive - Inside A Modern 14nm SoC",
    "author" = "Andrei Frumusanu",
    "date" = "2015-06-29 6:00 EST",
    "site" = "AnandTech",
    "URL" = "https://www.anandtech.com/show/9330/exynos-7420-deep-dive/5"
  )
)
print(basic)
```

```{r in-pw-dat}
# [7420 pw] input power consumption data
serialized_JSON <- '
{
  "A53": {
    "freq": [ 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500 ],
    "1 core": [ 0.035, 0.046, 0.066, 0.089, 0.116, 0.123, 0.142, 0.182, 0.235, 0.277, 0.322, 0.367 ],
    "2 cores": [ 0.066, 0.078, 0.103, 0.140, 0.166, 0.212, 0.249, 0.319, 0.389, 0.451, 0.531, 0.606 ],
    "3 cores": [ 0.068, 0.097, 0.129, 0.165, 0.209, 0.273, 0.326, 0.415, 0.490, 0.597, 0.707, 0.863 ],
    "4 cores": [ 0.104, 0.132, 0.172, 0.225, 0.270, 0.340, 0.391, 0.491, 0.606, 0.699, 0.859, 1.026 ]
  },
  "A57": {
    "freq": [ 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100 ],
    "1 core": [ 0.26, 0.30, 0.33, 0.38, 0.46, 0.52, 0.62, 0.66, 0.78, 0.87, 1.05, 1.24, 1.48, 1.62 ],
    "2 cores": [ 0.45, 0.52, 0.61, 0.72, 0.83, 0.98, 1.17, 1.31, 1.55, 1.69, 1.90, 2.28, 2.63, 2.97 ],
    "3 cores": [ 0.68, 0.75, 0.90, 1.03, 1.26, 1.40, 1.67, 1.85, 2.12, 2.33, 2.77, 3.25, 3.69, 4.19 ],
    "4 cores": [ 0.843, 0.969, 1.153, 1.330, 1.590, 1.793, 1.964, 2.254, 2.621, 3.089, 3.641, 4.111, 4.781, 5.481 ]
  }
}
'
print(serialized_JSON)
dat <- jsonlite::fromJSON(serialized_JSON)
```

```{r plot-pw-curves}
# [7420 pw] plot power consumption curves
library(ggplot2)
param_annotation_off_x <- 75
p <- ggplot() +
  geom_line(aes(x = dat$A53$freq, y = dat$A53$`1 core`), color = "blue") +
  geom_line(aes(x = dat$A53$freq, y = dat$A53$`2 cores`), color = "green") +
  geom_line(aes(x = dat$A53$freq, y = dat$A53$`3 cores`), color = "orange") +
  geom_line(aes(x = dat$A53$freq, y = dat$A53$`4 cores`), color = "red") +
  labs(
    title = "Exynos 7420 Power Consumption Curves (Cortex-A53)",
    x = "Frequency (MHz)", y = "Power Consumption (W)",
    color = "Active Cores"
  ) +
  theme_minimal() +
  annotate("text", x = 1500 + param_annotation_off_x, y = 0.367, label = "1 core", color = "blue") +
  annotate("text", x = 1500 + param_annotation_off_x, y = 0.606, label = "2 cores", color = "green") +
  annotate("text", x = 1500 + param_annotation_off_x, y = 0.863, label = "3 cores", color = "orange") +
  annotate("text", x = 1500 + param_annotation_off_x, y = 1.026, label = "4 cores", color = "red")
q <- ggplot() +
  geom_line(aes(x = dat$A57$freq, y = dat$A57$`1 core`), color = "blue") +
  geom_line(aes(x = dat$A57$freq, y = dat$A57$`2 cores`), color = "green") +
  geom_line(aes(x = dat$A57$freq, y = dat$A57$`3 cores`), color = "orange") +
  geom_line(aes(x = dat$A57$freq, y = dat$A57$`4 cores`), color = "red") +
  labs(
    title = "Exynos 7420 Power Consumption Curves (Cortex-A57)",
    x = "Frequency (MHz)", y = "Power Consumption (W)",
    color = "Active Cores"
  ) +
  theme_minimal() +
  annotate("text", x = 2100 + param_annotation_off_x, y = 1.62, label = "1 core", color = "blue") +
  annotate("text", x = 2100 + param_annotation_off_x, y = 2.97, label = "2 cores", color = "green") +
  annotate("text", x = 2100 + param_annotation_off_x, y = 4.19, label = "3 cores", color = "orange") +
  annotate("text", x = 2100 + param_annotation_off_x, y = 5.481, label = "4 cores", color = "red")
print(p)
print(q)
```

```{r regression}
# [7420 pw] regression
library(foreach)
core_configs <- c("1 core", "2 cores", "3 cores", "4 cores")
model <- list()
tmp <- foreach(core = core_configs) %do% {
  lm_A53 <- lm(dat$A53[[core]] ~ dat$A53$freq)
  lm_A57 <- lm(dat$A57[[core]] ~ dat$A57$freq)
  p <- length(model) + 1
  model[[p]] <- summary(lm_A53)
  model[[p + 1]] <- summary(lm_A57)
}
print(model)
```
