```{r a-ls}
# [param in cell nb] a list

a_list = c('a', 'b', 'c', 'd')
```

```{r proc-a-ls}
# [param in cell nb] process a list

b_list = c()
for (elem in a_list) {
    b_list[[length(b_list) + 1]] = elem + 32
}
```

```{r concat}
# [param in cell nb] concat

res = ''
for (elem in b_list) {
    res = paste0(res, elem)
}
```

```{r verage}
# [param in cell nb] verage

a = 2
numbers  = c(a, 4, 6, 8, 10)
```

```{r bb}
# [param in cell nb] bb

ave = mean(numbers)
```

```{r}
# params

```

```{r param-chk}
# [param in cell nb] Param check

param_density = 1

if (param_density == 1) {
    param_CountingStrategy = 'density0'
}

# check if mandatory fields are present
diameterofsedimentationchamber = 'diameterofsedimentationchamber'
```

```{r prt}
# [param in cell nb] print 

print(param_biovolume)
param_totalbiovolume
param_density
param_surfacearea
param_surfacevolumeratio
param_cellcarboncontent
param_totalcarboncontent
param_CountingStrategy

print(diameterofsedimentationchamber)
diameterofsedimentationchamber
diameteroffieldofview
transectcounting
numberofcountedfields
numberoftransects
settlingvolume
dilutionfactor
```
